services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5005:5005'
    environment:
      - TAPSILAT_API_KEY=${TAPSILAT_API_KEY}
      - GIN_MODE=debug
      - PORT=5005
    working_dir: /app
    networks:
      - tapsilat_network

networks:
  tapsilat_network:
    driver: bridge
